# Generated by Django 6.0 on 2025-12-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaLingkungan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_jalan", models.CharField(max_length=100)),
                ("rt_rw", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Berita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("isi", models.TextField()),
                ("tanggal_upload", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlamatWarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Rumah", max_length=50)),
                (
                    "detail_lain",
                    models.TextField(verbose_name="Detail (No Rumah/Patokan)"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alamat_warga",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.arealingkungan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jadwal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hari_tanggal", models.DateTimeField()),
                ("keterangan", models.CharField(blank=True, max_length=100)),
                (
                    "area_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.arealingkungan",
                    ),
                ),
                (
                    "kurir",
                    models.ForeignKey(
                        limit_choices_to={"profilpengguna__peran": "kurir"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermintaanJemput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis_sampah",
                    models.CharField(
                        choices=[
                            ("plastik", "Plastik (Botol, Gelas, Kemasan)"),
                            ("kertas", "Kertas / Kardus"),
                            ("logam", "Logam / Kaleng"),
                            ("organik", "Organik (Sisa Makanan)"),
                            ("campur", "Lainnya / Campur"),
                        ],
                        default="campur",
                        max_length=20,
                    ),
                ),
                ("tanggal_jemput", models.DateField()),
                ("catatan", models.TextField(blank=True, null=True)),
                ("berat_real", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("menunggu", "Menunggu Kurir"),
                            ("dijemput", "Proses Jemput"),
                            ("selesai", "Selesai"),
                        ],
                        default="menunggu",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alamat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.alamatwarga",
                    ),
                ),
                (
                    "kurir_pemeriksa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tugas_kurir",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pemohon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_jemput",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilPengguna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peran",
                    models.CharField(
                        choices=[
                            ("warga", "Warga"),
                            ("kurir", "Kurir"),
                            ("admin_sajiwa", "Admin Sajiwa"),
                        ],
                        default="warga",
                        max_length=20,
                    ),
                ),
                ("no_hp", models.CharField(blank=True, max_length=15, null=True)),
                ("poin", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "tipe",
                    models.CharField(
                        choices=[("masuk", "Uang Masuk"), ("keluar", "Uang Keluar")],
                        default="masuk",
                        max_length=10,
                    ),
                ),
                ("keterangan", models.CharField(max_length=100)),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
