# Generated by Django 6.0 on 2025-12-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permintaanjemput",
            name="waktu_jemput",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permintaanjemput",
            name="jenis_sampah",
            field=models.CharField(
                choices=[
                    ("plastik", "Plastik"),
                    ("kertas", "Kertas/Kardus"),
                    ("logam", "Kaleng/Logam"),
                    ("campur", "Campuran/Lainnya"),
                ],
                default="campur",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permintaanjemput",
            name="status",
            field=models.CharField(
                choices=[
                    ("menunggu", "Menunggu Jadwal"),
                    ("dijemput", "Terjadwal & Dijemput"),
                    ("selesai", "Selesai"),
                ],
                default="menunggu",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permintaanjemput",
            name="tanggal_jemput",
            field=models.DateField(blank=True, null=True),
        ),
    ]
