# Generated by Django 6.0 on 2025-12-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_permintaanjemput_waktu_jemput_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alamatwarga",
            name="detail_lain",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="permintaanjemput",
            name="kurir_pemeriksa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="permintaanjemput",
            name="status",
            field=models.CharField(
                choices=[
                    ("menunggu", "Menunggu Jadwal"),
                    ("dijemput", "Terjadwal & Proses"),
                    ("selesai", "Selesai"),
                ],
                default="menunggu",
                max_length=20,
            ),
        ),
    ]
