# Generated by Django 6.0 on 2025-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_alamatwarga_detail_lain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permintaanjemput",
            name="jenis_sampah",
            field=models.CharField(
                choices=[
                    ("plastik", "Plastik (Botol/Gelas)"),
                    ("kertas", "Kertas / Kardus"),
                    ("logam", "Kaleng / Logam"),
                    ("kaca", "Kaca / Beling"),
                    ("elektronik", "E-Waste / Elektronik"),
                    ("minyak", "Minyak Jelantah"),
                    ("tekstil", "Pakaian / Tekstil"),
                    ("campur", "Campuran / Lainnya"),
                ],
                default="campur",
                max_length=20,
            ),
        ),
    ]
