# Generated by Django 6.0 on 2025-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_permintaanjemput_jenis_sampah"),
    ]

    operations = [
        migrations.AddField(
            model_name="berita",
            name="gambar",
            field=models.ImageField(blank=True, null=True, upload_to="berita/"),
        ),
    ]
